### ISSUE TITLE
Problem with the Serializer on 1.21.3+

### ISSUE THREAD

**Issue by RedstoneFuture** [Butzlabben/missilewars#140]
**Describe the bug**

https://bytebin.lucko.me/SPot1U4wMU (`fasterxml.jackson... 2.16.2`)
https://bytebin.lucko.me/6eD1xrFZWp (`fasterxml.jackson... 2.18.2`)

**To Reproduce**
Error on startup.

**Server (please complete the following information):**

- OS: Linux
- Minecraft version 1.21.3
- Java version 21
- Version 5.0.0-rc.1

**Additional context**
Full reworking possible.

**Comment by RedstoneFuture** [comment]
The error does not occur in PaperMC `1.21.1`, but in `1.21.3+`.

```
[18:04:56] [Server thread/ERROR]: Error occurred while enabling MissileWars v5.0.0-rc.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.JsonToken com.fasterxml.jackson.dataformat.yaml.YAMLParser._updateTokenToNull()'
	at MissileWars-5.0.0-rc.1.jar/com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:575) ~[MissileWars-5.0.0-rc.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761) ~[jackson-databind-2.13.4.2.jar:2.13.4.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667) ~[jackson-databind-2.13.4.2.jar:2.13.4.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.4.2.jar:2.13.4.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[jackson-databind-2.13.4.2.jar:2.13.4.2]
	at MissileWars-5.0.0-rc.1.jar/de.butzlabben.missilewars.util.serialization.Serializer.yamlToJson(Serializer.java:119) ~[MissileWars-5.0.0-rc.1.jar:?]
	at MissileWars-5.0.0-rc.1.jar/de.butzlabben.missilewars.util.serialization.Serializer.deserialize(Serializer.java:67) ~[MissileWars-5.0.0-rc.1.jar:?]
	at MissileWars-5.0.0-rc.1.jar/de.butzlabben.missilewars.game.Arenas.load(Arenas.java:68) ~[MissileWars-5.0.0-rc.1.jar:?]
	at MissileWars-5.0.0-rc.1.jar/de.butzlabben.missilewars.initialization.GamesInitialization.initialize(GamesInitialization.java:15) ~[MissileWars-5.0.0-rc.1.jar:?]
	at MissileWars-5.0.0-rc.1.jar/de.butzlabben.missilewars.MissileWars.onEnable(MissileWars.java:93) ~[MissileWars-5.0.0-rc.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:04:56] [Server thread/INFO]: [MissileWars] Disabling MissileWars v5.0.0-rc.1

```
