### ISSUE TITLE
Plugin Update 1.19.2

### ISSUE THREAD

**Issue by AlloryDante** [Butzlabben/missilewars#54]
Hello, please update this wonderfull plugin to 1.19.2.Thank you in avance

```
[19:09:30 ERROR]: Error occurred while enabling MissileWars v4.3.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.butzlabben.missilewars.game.GameState.ordinal()" because "state" is null
        at de.butzlabben.missilewars.util.MotdManager.updateMOTD(MotdManager.java:44) ~[MissileWars-4.3.1.jar:?]
        at de.butzlabben.missilewars.game.Game.<init>(Game.java:144) ~[MissileWars-4.3.1.jar:?]
        at de.butzlabben.missilewars.game.GameManager.restartGame(GameManager.java:125) ~[MissileWars-4.3.1.jar:?]
        at de.butzlabben.missilewars.game.GameManager.loadGames(GameManager.java:98) ~[MissileWars-4.3.1.jar:?]
        at de.butzlabben.missilewars.game.GameManager.loadGames(GameManager.java:75) ~[MissileWars-4.3.1.jar:?]
        at de.butzlabben.missilewars.MissileWars.onEnable(MissileWars.java:101) ~[MissileWars-4.3.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-299]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-299]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-299]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]



```

**Comment by RedstoneFuture** [comment]
Already fixed: https://github.com/Butzlabben/missilewars/issues/37
It's not a 1.19.x problem.
