### ISSUE TITLE
Error when starting the plugin

### ISSUE THREAD

**Issue by Sayrix** [Butzlabben/missilewars#86]
**Describe the bug**
When the server starts, there are an error and the plugin can't be enabled

**To Reproduce**
1. Paper 411 (1.17.1)
2. Java 17J9 (ghcr.io/pterodactyl/yolks:java_17J9)
3. Start the server

**Error:**
```
[18:10:58 INFO]: [MissileWars] Enabling MissileWars v4.5.0
[18:10:58 INFO]: [MW] Boot | This server is running MissileWars v4.5.0 by Butzlabben
[18:10:58 INFO]: [MW] Boot | Loading properties...
[18:10:58 INFO]: [MW] Boot | Registering commands
[18:10:58 INFO]: [MissileWars] [ACF] Enabled Asynchronous Tab Completion Support!
[18:10:59 ERROR]: Error occurred while enabling MissileWars v4.5.0 (Is it up to date?)
java.lang.NoSuchMethodError: org/yaml/snakeyaml/parser/ParserImpl.<init>(Lorg/yaml/snakeyaml/reader/StreamReader;Lorg/yaml/snakeyaml/LoaderOptions;)V (loaded from file:/home/container/cache/patched_1.17.1.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@174dd55d) called from class com.fasterxml.jackson.dataformat.yaml.YAMLParser (loaded from file:/home/container/plugins/MissileWars-4.5.0.jar by PluginClassLoader{plugin=MissileWars v4.5.0, pluginEnabled=true, url=plugins/MissileWars-4.5.0.jar}).
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:193) ~[MissileWars-4.5.0.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:509) ~[MissileWars-4.5.0.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:413) ~[MissileWars-4.5.0.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:386) ~[MissileWars-4.5.0.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[MissileWars-4.5.0.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[MissileWars-4.5.0.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[MissileWars-4.5.0.jar:?]
        at de.butzlabben.missilewars.util.serialization.Serializer.yamlToJson(Serializer.java:120) ~[MissileWars-4.5.0.jar:?]
        at de.butzlabben.missilewars.util.serialization.Serializer.deserialize(Serializer.java:68) ~[MissileWars-4.5.0.jar:?]
        at de.butzlabben.missilewars.game.Arenas.load(Arenas.java:68) ~[MissileWars-4.5.0.jar:?]
        at de.butzlabben.missilewars.MissileWars.onEnable(MissileWars.java:103) ~[MissileWars-4.5.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:857) ~[?:?]
[18:10:59 INFO]: [MissileWars] Disabling MissileWars v4.5.0
[18:10:59 INFO]: [MW] Error | [MySQL] Connection does not exist or was already closed
```

**Comment by daniel-naegele** [comment]
Does this error also occurr on 4.4.2?

**Comment by Sayrix** [comment]
v4.5.0

**Comment by daniel-naegele** [comment]
Yes I know that it occurrs on 4.5.0, but the question is, if it also occurrs on 4.4.2

**Comment by Sayrix** [comment]
Hmm i will try

**Comment by Sayrix** [comment]
Yep in 4.4.2 it works

**Comment by Sayrix** [comment]
Hi in 4.5.1 it still don't work, here is the error:
```
[14:10:56 INFO]: [MissileWars] Enabling MissileWars v4.5.1
[14:10:56 INFO]: [MW] Boot | This server is running MissileWars v4.5.1 by Butzlabben
[14:10:56 INFO]: [MW] Boot | Loading properties...
[14:10:56 INFO]: [MW] Boot | Registering commands
[14:10:56 INFO]: [MissileWars] [ACF] Enabled Asynchronous Tab Completion Support!
[14:10:56 ERROR]: Error occurred while enabling MissileWars v4.5.1 (Is it up to date?)
java.lang.NoSuchMethodError: com/fasterxml/jackson/dataformat/yaml/YAMLFactory._createContentReference(Ljava/lang/Object;)Lcom/fasterxml/jackson/core/io/ContentReference; (loaded from file:/home/container/plugins/MissileWars-4.5.1.jar by PluginClassLoader{plugin=MissileWars v4.5.1, pluginEnabled=true, url=plugins/MissileWars-4.5.1.jar}) called from class com.fasterxml.jackson.dataformat.yaml.YAMLFactory (loaded from file:/home/container/plugins/MissileWars-4.5.1.jar by PluginClassLoader{plugin=MissileWars v4.5.1, pluginEnabled=true, url=plugins/MissileWars-4.5.1.jar}).
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:412) ~[MissileWars-4.5.1.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:386) ~[MissileWars-4.5.1.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[MissileWars-4.5.1.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548) ~[MissileWars-4.5.1.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516) ~[MissileWars-4.5.1.jar:?]
        at de.butzlabben.missilewars.util.serialization.Serializer.yamlToJson(Serializer.java:120) ~[MissileWars-4.5.1.jar:?]
        at de.butzlabben.missilewars.util.serialization.Serializer.deserialize(Serializer.java:68) ~[MissileWars-4.5.1.jar:?]
        at de.butzlabben.missilewars.game.Arenas.load(Arenas.java:68) ~[MissileWars-4.5.1.jar:?]
        at de.butzlabben.missilewars.MissileWars.onEnable(MissileWars.java:103) ~[MissileWars-4.5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:857) ~[?:?]
[14:10:56 INFO]: [MissileWars] Disabling MissileWars v4.5.1
[14:10:56 INFO]: [MW] Error | [MySQL] Connection does not exist or was already closed
```
